# Cell Type Enrichment Functions
# jmtools package


#' Filter marker genes for cell type enrichment analysis
#'
#' Applies quality thresholds to a raw single-cell marker gene data frame,
#' returning only high-confidence positive markers. The filtered output is
#' intended to be passed to [plot_celltype_effect_sizes()] and
#' [plot_celltype_dotplot()], and used to build gene sets for GSEA or ORA.
#'
#' @param marker_genes Data frame of raw marker genes containing at minimum a
#'   cluster column, a gene symbol column, and the four QC columns described
#'   below.
#' @param min_avg_log2fc Minimum average log2 fold change. Default: 0.25.
#' @param min_auc Minimum AUC (area under the ROC curve). AUC > 0.8 is the
#'   primary positive-marker filter. Default: 0.8.
#' @param max_padj Maximum adjusted p-value. Default: 0.05.
#' @param min_pct_1 Minimum fraction of cells in the cluster expressing the
#'   gene. Avoids markers driven by a tiny minority of cells. Default: 0.10.
#' @param cluster_col Column containing cell type labels. Default: `"cluster"`.
#' @param gene_col Column containing gene symbols. Default: `"gene"`.
#' @param log2fc_col Column containing average log2 fold change. Default:
#'   `"avg_log2fc"`.
#' @param auc_col Column containing the AUC (area under the ROC curve), as
#'   output by `Seurat::FindAllMarkers(test.use = "roc")`. Default: `"my_auc"`.
#' @param padj_col Column containing adjusted p-values. Default: `"padj"`.
#' @param pct1_col Column containing the fraction of cells expressing the gene.
#'   Default: `"pct_1"`.
#'
#' @return A data frame of the same structure as `marker_genes`, retaining only
#'   rows that pass all thresholds.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' marker_genes_raw <- read.csv("heart_cell_atlas_v2_l1_marker_genes.csv")
#' markers_filtered <- filter_marker_genes(marker_genes_raw)
#' }
#'
#' @details
#' The `marker_genes` data frame can be as generated by
#' `Seurat::FindAllMarkers()`.
#'
#' Pre-processed marker gene CSVs for the Human Heart Cell Atlas v2 are
#' available on the group drive at:
#' \itemize{
#'   \item Level 1 (13 cell types):
#'     \code{/Volumes/groupdir/SUN-BMI-CardiacProteomics/scRNAseq_datasets/JM/atlas_snRNAseq/results/heart_cell_atlas_v2/heart_cell_atlas_v2_all_cells_annotated_predicted_celltype_l1_marker_genes.csv}
#'   \item Level 2 (finer annotations):
#'     \code{/Volumes/groupdir/SUN-BMI-CardiacProteomics/scRNAseq_datasets/JM/atlas_snRNAseq/results/heart_cell_atlas_v2/heart_cell_atlas_v2_all_cells_annotated_predicted_celltype_l2_marker_genes.csv}
#' }
#'
#' @seealso [plot_celltype_effect_sizes()], [plot_celltype_dotplot()],
#'   [plot_gsea_bars()]
filter_marker_genes <- function(marker_genes,
                                min_avg_log2fc = 0.25,
                                min_auc        = 0.8,
                                max_padj       = 0.05,
                                min_pct_1      = 0.10,
                                cluster_col    = "cluster",
                                gene_col       = "gene",
                                log2fc_col     = "avg_log2fc",
                                auc_col        = "my_auc",
                                padj_col       = "padj",
                                pct1_col       = "pct_1") {

  required_cols <- c(cluster_col, gene_col, log2fc_col, auc_col, padj_col, pct1_col)
  missing_cols  <- setdiff(required_cols, names(marker_genes))
  if (length(missing_cols) > 0) {
    stop("Missing columns in marker_genes: ", paste(missing_cols, collapse = ", "))
  }

  out <- marker_genes[
    marker_genes[[log2fc_col]] > min_avg_log2fc &
    marker_genes[[auc_col]]    > min_auc        &
    marker_genes[[padj_col]]   < max_padj       &
    marker_genes[[pct1_col]]   > min_pct_1      ,
  ]

  if (nrow(out) == 0) {
    stop("No marker genes remain after filtering. Consider relaxing filter thresholds.")
  }

  message("filter_marker_genes: ", nrow(out), " markers retained across ",
          length(unique(out[[cluster_col]])), " cell types.")

  out
}


#' Plot effect size distributions by cell type marker set
#'
#' Creates a violin and boxplot for each cell type, showing the distribution of
#' per-protein effect sizes (e.g. Hedges' g or log2 fold change) across that
#' cell type's detected marker proteins. The join between marker genes and limma
#' results is performed internally.
#'
#' @param marker_genes Data frame of **filtered** marker genes, as returned by
#'   [filter_marker_genes()]. Must contain at least `cluster_col` and
#'   `gene_col`.
#' @param limma_results Data frame of limma differential abundance results
#'   containing at least `gene_symbol_col` and `effect_col`.
#' @param effect_col Column in `limma_results` containing the effect size to
#'   plot. Default: `"hedges_g"`. Use `"log_fc"` for log2 fold change.
#' @param cluster_col Column in `marker_genes` containing cell type labels.
#'   Default: `"cluster"`.
#' @param gene_col Column in `marker_genes` containing gene symbols. Default:
#'   `"gene"`.
#' @param gene_symbol_col Column in `limma_results` containing gene symbols.
#'   Default: `"gene_symbol"`.
#' @param x_label Label for the x-axis. If `NULL` (default), a label is
#'   derived automatically from `effect_col`: `"hedges_g"` becomes
#'   `"Hedges' g"`, `"log_fc"` becomes `"log2 fold change"`.
#' @param title Plot title. Default: `"Effect size distribution by cell type
#'   marker set"`.
#'
#' @return A ggplot2 object.
#'
#' @details
#' Proteins with `NA` or multi-mapped gene symbols (containing `";"`) are
#' excluded. Where the same gene symbol appears more than once in
#' `limma_results`, the first occurrence is kept.
#'
#' Cell types are ordered on the y-axis by their median effect size (ascending).
#'
#' @export
#'
#' @examples
#' \dontrun{
#' plot_celltype_effect_sizes(markers_filtered, limma_results)
#' plot_celltype_effect_sizes(markers_filtered, limma_results, effect_col = "log_fc")
#' }
#'
#' @seealso [filter_marker_genes()], [plot_gsea_bars()]
#'
#' @importFrom ggplot2 geom_violin geom_boxplot geom_vline labs
#' @importFrom rlang .data
plot_celltype_effect_sizes <- function(marker_genes,
                                       limma_results,
                                       effect_col      = "hedges_g",
                                       cluster_col     = "cluster",
                                       gene_col        = "gene",
                                       gene_symbol_col = "gene_symbol",
                                       x_label         = NULL,
                                       title           = "Effect size distribution by cell type marker set") {

  missing_marker <- setdiff(c(cluster_col, gene_col), names(marker_genes))
  if (length(missing_marker) > 0) {
    stop("Missing columns in marker_genes: ", paste(missing_marker, collapse = ", "))
  }
  missing_limma <- setdiff(c(gene_symbol_col, effect_col), names(limma_results))
  if (length(missing_limma) > 0) {
    stop("Missing columns in limma_results: ", paste(missing_limma, collapse = ", "))
  }

  # Deduplicate limma results: remove NA and multi-mapped gene symbols
  limma_clean <- limma_results[
    !is.na(limma_results[[gene_symbol_col]]) &
    !grepl(";", limma_results[[gene_symbol_col]], fixed = TRUE),
  ]
  limma_clean <- limma_clean[!duplicated(limma_clean[[gene_symbol_col]]), ]

  # Inner join on gene symbol
  marker_subset <- marker_genes[, c(cluster_col, gene_col), drop = FALSE]
  limma_subset  <- limma_clean[, c(gene_symbol_col, effect_col), drop = FALSE]

  joined <- merge(marker_subset, limma_subset,
                  by.x = gene_col, by.y = gene_symbol_col,
                  all.x = FALSE)

  if (nrow(joined) == 0) {
    stop("No genes matched between marker_genes and limma_results.")
  }

  # Order cell types by median effect size (ascending)
  median_by_cluster  <- tapply(joined[[effect_col]], joined[[cluster_col]],
                               stats::median, na.rm = TRUE)
  joined[[cluster_col]] <- factor(joined[[cluster_col]],
                                  levels = names(sort(median_by_cluster)))

  # Build x-axis label if not supplied
  if (is.null(x_label)) {
    default_labels <- c(hedges_g = "Hedges' g", log_fc = "log2 fold change")
    x_label <- if (effect_col %in% names(default_labels)) {
      default_labels[[effect_col]]
    } else {
      effect_col
    }
  }

  ggplot2::ggplot(joined, ggplot2::aes(
    x = .data[[effect_col]],
    y = .data[[cluster_col]]
  )) +
    ggplot2::geom_vline(xintercept = 0, linetype = "dashed", colour = "grey40") +
    ggplot2::geom_violin(fill = "grey85", colour = NA, scale = "width", width = 0.8) +
    ggplot2::geom_boxplot(outlier.shape = NA, width = 0.2,
                          fill = "white", colour = "grey30") +
    ggplot2::labs(x = x_label, y = NULL, title = title) +
    theme_jm()
}


#' Plot a marker gene dot plot by cell type
#'
#' Creates a dot plot of a supplied set of marker genes, where dot size encodes
#' the fraction of cells expressing the gene and dot colour encodes scaled
#' average expression. Expression is scaled per gene across all cell types
#' present in `marker_genes`, so the colour scale reflects the full range of
#' expression.
#'
#' @param marker_genes Data frame of **raw** (unfiltered) marker genes,
#'   containing expression data for all cell types. Used only for looking up
#'   expression values; gene selection is controlled by `genes`.
#' @param genes Character vector of gene symbols to plot, in the desired
#'   left-to-right display order on the x-axis. Typically derived from a
#'   filtered marker gene data frame, e.g. via [filter_marker_genes()] and
#'   manual selection of top markers per cell type.
#' @param cluster_col Column in `marker_genes` for cell type labels. Default:
#'   `"cluster"`.
#' @param gene_col Column in `marker_genes` for gene symbols. Default: `"gene"`.
#' @param pct1_col Column for fraction of cells expressing the gene. Default:
#'   `"pct_1"`.
#' @param avg_expr_col Column for average expression (used for colour scaling).
#'   Default: `"avg_expr"`.
#' @param title Plot title. Default: `"Top cell type marker genes"`.
#'
#' @return A ggplot2 object.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' markers_filtered <- filter_marker_genes(marker_genes_raw)
#' top_genes <- tapply(markers_filtered$gene, markers_filtered$cluster,
#'                     function(g) head(g, 5))
#' genes_to_plot <- unique(unlist(top_genes))
#' plot_celltype_dotplot(marker_genes_raw, genes = genes_to_plot)
#' }
#'
#' @seealso [filter_marker_genes()], [plot_gsea_bars()]
#'
#' @importFrom ggplot2 geom_point scale_colour_gradient2 scale_size_continuous scale_x_discrete guide_axis element_line element_text labs theme
#' @importFrom rlang .data
#' @importFrom stats ave
plot_celltype_dotplot <- function(marker_genes,
                                  genes,
                                  cluster_col  = "cluster",
                                  gene_col     = "gene",
                                  pct1_col     = "pct_1",
                                  avg_expr_col = "avg_expr",
                                  title        = "Top cell type marker genes") {

  if (!is.character(genes) || length(genes) == 0) {
    stop("'genes' must be a non-empty character vector.")
  }

  required_cols <- c(cluster_col, gene_col, pct1_col, avg_expr_col)
  missing_cols  <- setdiff(required_cols, names(marker_genes))
  if (length(missing_cols) > 0) {
    stop("Missing columns in marker_genes: ", paste(missing_cols, collapse = ", "))
  }

  dotplot_data <- marker_genes[marker_genes[[gene_col]] %in% genes, ]

  if (nrow(dotplot_data) == 0) {
    stop("None of the supplied genes were found in marker_genes.")
  }

  # Scale avg_expr per gene across all cell types
  dotplot_data$scaled_expr <- ave(
    dotplot_data[[avg_expr_col]],
    dotplot_data[[gene_col]],
    FUN = function(x) as.numeric(scale(x))
  )

  dotplot_data[[gene_col]] <- factor(dotplot_data[[gene_col]], levels = genes)

  ggplot2::ggplot(dotplot_data, ggplot2::aes(
    x = .data[[gene_col]],
    y = .data[[cluster_col]]
  )) +
    ggplot2::geom_point(ggplot2::aes(
      size   = .data[[pct1_col]],
      colour = .data$scaled_expr
    )) +
    ggplot2::scale_colour_gradient2(
      low      = "#2166ac",
      mid      = "white",
      high     = "#d73027",
      midpoint = 0,
      name     = "Scaled\nexpression"
    ) +
    ggplot2::scale_size_continuous(name = "Fraction\nexpressing", range = c(0.5, 6)) +
    ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(angle = 90)) +
    ggplot2::labs(x = NULL, y = NULL, title = title) +
    theme_jm() +
    ggplot2::theme(
      panel.grid.major = ggplot2::element_line(colour = "grey90"),
      axis.text.x      = ggplot2::element_text(size = 7)
    )
}
